Update jenkinsFile

diff --git a/jenkinsFile b/jenkinsFile
--- a/jenkinsFile
+++ b/jenkinsFile
@@ -1,3 +1,4 @@
+
 pipeline {
     agent any
     environment {
@@ -20,6 +21,29 @@ pipeline {
             steps {
                 sh 'kubectl apply -f k8s/deployment.yaml'
             }
+        }
+        stage('Configure with Ansible') {
+            steps {
+                sh '''
+                    ansible-playbook -i inventory/development playbooks/setup.yml
+                '''
+            }
+        }
+        stage('Check Nagios Monitoring') {
+            steps {
+                // Utilisation de Nagios pour surveiller le service déployé
+                sh '''
+                    curl --silent --show-error --fail http://localhost:8000/health || echo "Service not healthy!"
+                '''
+            }
+        }
+    }
+    post {
+        success {
+            echo 'Pipeline completed successfully!'
+        }
+        failure {
+            echo 'Pipeline failed.'
         }
     }
 }
